apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mysql-init
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              sleep 20 &&
              mysql -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD < /scripts/library.sql
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: sql-script
              mountPath: /scripts
      volumes:
        - name: sql-script
          configMap:
            name: library-sql
